package app.util;

public enum URI {
	
	/** URI de l'assembleur */
	DYNAMIC_ASSEMBLEUR_URI("DYNAMIC_ASSEMBLEUR_URI"),
	
	/** URI des composants */
	CONTROLEUR_URI("CONTROLEUR_URI"),
	FRIGO_URI("FRIGO_URI"),
	LAVELIGNE_URI("LAVELIGNE_URI"),
	ORDINATEUR_URI("ORDINATEUR_URI"),
	BATTERIE_URI("BATTERIE_URI"),
	PANNEAUSOLAIRE_URI("PANNEAUSOLAIRE_URI"),
	COMPTEUR_URI("COMPTEUR_URI"),
	
	/** URI des ports sortants controleur */
	CONTROLEUR_OP_FRIGO_URI("CONTROLEUR_OP_FRIGO_URI"),
	CONTROLEUR_OP_ORDINATEUR_URI("CONTROLEUR_OP_ORDINATEUR_URI"),
	CONTROLEUR_OP_LAVELINGE_URI("CONTROLEUR_OP_LAVELINGE_URI"),
	CONTROLEUR_OP_COMPTEUR_URI("CONTROLEUR_OP_COMPTEUR_URI"),
	CONTROLEUR_OP_PANNEAUSOLAIRE_URI("CONTROLEUR_OP_PANNEAUSOLAIRE_URI"),
	CONTROLEUR_OP_BATTERIE_URI("CONTROLEUR_OP_BATTERIE_URI"),
	
	/** URI des ports sortants appareils et unites de productions vers controleur */
	FRIGO_CONTROLEUR_OP_URI("FRIGO_CONTROLEUR_OP_URI"),
	LAVELINGE_CONTROLEUR_OP_URI("LAVELINGE_CONTROLEUR_OP_URI"),
	ORDINATEUR_CONTROLEUR_OP_URI("ORDINATEUR_CONTROLEUR_OP_URI"),
	PANNEAUSOLAIRE_CONTROLEUR_OP_URI("PANNEAUSOLAIRE_CONTROLEUR_OP_URI"),
	BATTERIE_CONTROLEUR_OP_URI("BATTERIE_CONTROLEUR_OP_URI"),
	
	/** URI des ports sortants appareils et unites de productions vers compteur */
	FRIGO_COMPTEUR_OP_URI("FRIGO_COMPTEUR_OP_URI"),
	LAVELINGE_COMPTEUR_OP_URI("LAVELINGE_COMPTEUR_OP_URI"),
	ORDINATEUR_COMPTEUR_OP_URI("ORDINATEUR_COMPTEUR_OP_URI"),
	PANNEAUSOLAIRE_COMPTEUR_OP_URI("PANNEAUSOLAIRE_COMPTEUR_OP_URI"),
	BATTERIE_COMPTEUR_OP_URI("BATTERIE_COMPTEUR_OP_URI");
	
//	/** URI des ports entrants appareils et unites de productions pour l'assembleur */
//	FRIGO_INP_ASSEMBLEUR_URI("FRIGO_INP_ASSEMBLEUR_URI"),
//	LAVELINGE_INP_ASSEMBLEUR_URI("LAVELINGE_INP_ASSEMBLEUR_URI"),
//	ORDINATEUR_INP_ASSEMBLEUR_URI("ORDINATEUR_INP_ASSEMBLEUR_URI"),
//	PANNEAUSOLAIRE_INP_ASSEMBLEUR_URI("PANNEAUSOLAIRE_INP_ASSEMBLEUR_URI"),
//	BATTERIE_INP_ASSEMBLEUR_URI("BATTERIE_INP_ASSEMBLEUR_URI");
//	
	private final String uri;
	 
    URI(String envUri) {
        this.uri = envUri;
    }
 
    public String getURI() {
        return uri;
    }
}
