#!/bin/bash

java -ea -cp 'jars/*':'bin/' -Djava.security.manager -Djava.security.policy=dcvm.policy app.DistributedCVM controleur config.xml &

java -ea -cp 'jars/*':'bin/' -Djava.security.manager -Djava.security.policy=dcvm.policy app.DistributedCVM compteur config.xml &

java -ea -cp 'jars/*':'bin/' -Djava.security.manager -Djava.security.policy=dcvm.policy app.DistributedCVM frigo config.xml &

java -ea -cp 'jars/*':'bin/' -Djava.security.manager -Djava.security.policy=dcvm.policy app.DistributedCVM ordinateur config.xml &

java -ea -cp 'jars/*':'bin/' -Djava.security.manager -Djava.security.policy=dcvm.policy app.DistributedCVM chargeur config.xml &

java -ea -cp 'jars/*':'bin/' -Djava.security.manager -Djava.security.policy=dcvm.policy app.DistributedCVM panneau config.xml &

java -ea -cp 'jars/*':'bin/' -Djava.security.manager -Djava.security.policy=dcvm.policy app.DistributedCVM batterie config.xml &